from setuptools import setup

setup(
    name='SensorDataProcessing',
    version='1.0.0',
    packages=['idna', 'pytz', 'yaml',
              'numpy', 'numpy.ma',
              'numpy.ma.tests', 'numpy.doc',
              'numpy.fft', 'numpy.fft.tests',
              'numpy.lib', 'numpy.lib.tests',
              'numpy.core', 'numpy.core.tests',
              'numpy.f2py', 'numpy.f2py.tests',
              'numpy.tests', 'numpy.compat',
              'numpy.compat.tests', 'numpy.linalg',
              'numpy.linalg.tests', 'numpy.random',
              'numpy.random.tests', 'numpy.testing',
              'numpy.testing.tests', 'numpy.testing._private',
              'numpy.distutils', 'numpy.distutils.tests',
              'numpy.distutils.command', 'numpy.distutils.fcompiler',
              'numpy.matrixlib', 'numpy.matrixlib.tests',
              'numpy.polynomial', 'numpy.polynomial.tests',
              'pandas', 'pandas.io',
              'pandas.io.sas', 'pandas.io.json',
              'pandas.io.formats', 'pandas.io.msgpack',
              'pandas.io.clipboard', 'pandas.api',
              'pandas.api.types', 'pandas.api.extensions',
              'pandas.core', 'pandas.core.util',
              'pandas.core.tools', 'pandas.core.arrays',
              'pandas.core.dtypes', 'pandas.core.sparse',
              'pandas.core.groupby', 'pandas.core.indexes',
              'pandas.core.reshape', 'pandas.core.internals',
              'pandas.core.computation', 'pandas.util',
              'pandas._libs', 'pandas._libs.tslibs',
              'pandas.tests', 'pandas.tests.io',
              'pandas.tests.io.sas', 'pandas.tests.io.json',
              'pandas.tests.io.parser', 'pandas.tests.io.formats',
              'pandas.tests.io.msgpack', 'pandas.tests.api',
              'pandas.tests.util', 'pandas.tests.frame',
              'pandas.tests.tools', 'pandas.tests.arrays',
              'pandas.tests.arrays.sparse',
              'pandas.tests.arrays.interval',
              'pandas.tests.arrays.categorical', 'pandas.tests.dtypes',
              'pandas.tests.dtypes.cast', 'pandas.tests.scalar',
              'pandas.tests.scalar.period',
              'pandas.tests.scalar.interval',
              'pandas.tests.scalar.timedelta',
              'pandas.tests.scalar.timestamp', 'pandas.tests.series',
              'pandas.tests.series.indexing', 'pandas.tests.sparse',
              'pandas.tests.sparse.frame', 'pandas.tests.sparse.series',
              'pandas.tests.tslibs', 'pandas.tests.generic',
              'pandas.tests.groupby', 'pandas.tests.groupby.aggregate',
              'pandas.tests.indexes', 'pandas.tests.indexes.multi',
              'pandas.tests.indexes.period',
              'pandas.tests.indexes.interval',
              'pandas.tests.indexes.datetimes',
              'pandas.tests.indexes.timedeltas', 'pandas.tests.reshape',
              'pandas.tests.reshape.merge', 'pandas.tests.tseries',
              'pandas.tests.tseries.offsets', 'pandas.tests.indexing',
              'pandas.tests.indexing.interval',
              'pandas.tests.indexing.multiindex', 'pandas.tests.plotting',
              'pandas.tests.resample', 'pandas.tests.extension',
              'pandas.tests.extension.base',
              'pandas.tests.extension.json',
              'pandas.tests.extension.arrow',
              'pandas.tests.extension.numpy_',
              'pandas.tests.extension.decimal', 'pandas.tests.internals',
              'pandas.tests.arithmetic', 'pandas.tests.reductions',
              'pandas.tests.computation', 'pandas.arrays',
              'pandas.compat', 'pandas.compat.numpy',
              'pandas.errors', 'pandas.tseries',
              'pandas.plotting', 'certifi',
              'chardet', 'chardet.cli', 'urllib3',
              'urllib3.util', 'urllib3.contrib',
              'urllib3.contrib._securetransport', 'urllib3.packages',
              'urllib3.packages.backports',
              'urllib3.packages.ssl_match_hostname', 'dateutil',
              'dateutil.tz', 'dateutil.parser',
              'dateutil.zoneinfo', 'requests',
              'pip-10.0.1-py3.7.egg.pip',
              'pip-10.0.1-py3.7.egg.pip._vendor',
              'pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'pip-10.0.1-py3.7.egg.pip._internal',
              'pip-10.0.1-py3.7.egg.pip._internal.req',
              'pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'pip-10.0.1-py3.7.egg.pip._internal.utils',
              'pip-10.0.1-py3.7.egg.pip._internal.models',
              'pip-10.0.1-py3.7.egg.pip._internal.commands',
              'pip-10.0.1-py3.7.egg.pip._internal.operations', 'IOOperations', 'Configuration',
              'DataProcessor'],
    url='',
    license='',
    author='Arun Thundyill Saseendran',
    author_email='thundyia@tcd.ie',
    description='Application to Parse Sensor Data'
)
